### ISSUE TITLE
Error in .norg filetype when the plugin is enabled when pressing enter in insert mode

### ISSUE THREAD

**Issue by auralisx** [altermo/ultimate-autopair.nvim#102]
Recently, I'm encountering an error with Ultimate-autopair.nvim specifically in files with the .norg filetype (The plugin works as expected in other file types). When I enter insert mode and try to press Enter to move to a new line, the following error message appears: 

`Error 10:28:32 PM msg_show.lua_error E315: ml_get: Invalid lnum: 27`

if i try to enter again, a message appears 

`10:28:36 PM msg_show.echo ...autopair.nvim/lua/ultimate-autopair/extension/escape.lua:23: attempt to index field 'line' (a nil value)
stack traceback:
    ...y/ultimate-autopair.nvim/lua/ultimate-autopair/debug.lua:77: in function '__index'
    ...autopair.nvim/lua/ultimate-autopair/extension/escape.lua:23: in function 'filter'
    ...autopair.nvim/lua/ultimate-autopair/extension/escape.lua:36: in function <...autopair.nvim/lua/ultimate-autopair/extension/escape.lua:35>
    [C]: in function 'xpcall'
    ...y/ultimate-autopair.nvim/lua/ultimate-autopair/debug.lua:97: in function 'run'
    ...zy/ultimate-autopair.nvim/lua/ultimate-autopair/core.lua:96: in function <...zy/ultimate-autopair.nvim/lua/ultimate-autopair/core.lua:87>
    [C]: in function 'nvim_eval'
    ....local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:181: in function 'solve'
    ....local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:154: in function <....local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:153>
`

This error occurs only when I press Enter in insert mode to move to a new line in .norg files. Interestingly, pressing Alt+Enter (a default Neorg keybinding) works fine, and I don’t encounter any issues with it. 

**Steps to Reproduce:**

1. Open a .norg file.
2. Enter insert mode.
3. Press Enter to create a new line.
4. Observe the error message above.

**Troubleshooting Attempts:**

- I tried disabling autopair for the .norg filetype using the following configuration:

``` lua 
{
  "altermo/ultimate-autopair.nvim",
  event = {
    "InsertEnter",
    "CmdlineEnter"
  },
  opts = {
    extensions = {
      filetype = {
        nft = {
          "TelescopePrompt",
          "Norg"
        }
      }
    }
  }
}
```
Despite this, the issue persists when Ultimate-autopair.nvim is enabled.

- When I disable Ultimate-autopair.nvim, everything works fine.
- I also have mini.pairs installed through lazyvim which was disabled in favor of ultimate-autopair.nvim. If I enable mini.pairs instead, I don’t encounter the error.

**Environment:**

    Neovim version: NVIM v0.10.2
    Ultimate-autopair.nvim version: v0.6 branch

**Additional Context:**
When I searched for the E315 error, I found that it is an internal Vim error related to invalid line numbers, which might indicate an internal issue. Given that the error appears specific to pressing Enter in .norg files, and doesn’t occur when mini.pairs is active or when Ultimate-autopair.nvim is disabled, I’m unsure if this is an issue with Ultimate-autopair.nvim itself or a conflict in my configuration.

Any guidance or suggestions on resolving this would be greatly appreciated!

**Comment by altermo** [comment]
(This is wrong, see below for correctness)
Here are my current findings:
Ultimate-autopair calls `vim.filetype.get_option` through `pcall` which launches a `FileType` event to Neorg with a temporary unloaded buffer.
Neorg expects a loaded buffer so throws an error which is watched by Ultimate-autopairs `pcall`, but the temporary buffer is not cleaned up.
Something happens (this is the part where I have no idea what) that makes it so that the unloaded buffer gets some lines, without making it loaded (by default when inserting text the unloaded buffer is loaded).
The cursor is set to one of these lines, which are not supposed to exist.
Nvim-cmp executes a keybinding, but because the cursor position is on a line that technically doesn't exist, E315 error.
The cursor position is still on a phantom line, so now Ultimate-autopair tries to work with it and errors in its own way.

**Comment by altermo** [comment]
A quick solution to not encounter the bug is to load unloaded buffers on FileType:
(It needs to be defined before all other FileType autocmds)
```lua
vim.api.nvim_create_autocmd('FileType',{callback=function (ev)
    if not vim.api.nvim_buf_is_loaded(ev.buf) then
        vim.fn.bufload(ev.buf)
    end
end})
```

**Comment by altermo** [comment]
This is a combination of three (maybe four) bugs: a Neorg bug, a Neovim bug, and an Ultimate-autopair bug:

1. The Neorg bug is that it errors if an autocmd passes in an unloaded buffer. (`vim.filetype.get_option` is the one that creates this unloaded buffer). And because of that the `vim.filetype.get_option` created buffer never gets cleaned up.

2. The Neovim bug is that if an abbreviation autocompletion is done in an unloaded buffer (in a specific way), it errors.

3. The Ultimate-autopair bug is the same as the Neorg bug, as it doesn't handle unloaded buffers well, that's what the second error is.

4. (Though, are you supposed to be able to view and interact with an unloaded buffer as if it were like any other buffer? This might be another Neovim bug.)

A minimal reproducible setup:
```lua
vim.api.nvim_create_autocmd('FileType',{callback=function (env)
    assert(vim.api.nvim_buf_is_loaded(env.buf))
end})

vim.keymap.set('i','\r',function ()
    pcall(vim.filetype.get_option,'A','lisp')
    return '\29\r'
end,{expr=true})

vim.cmd([[cnoreabbrev B C]])
```

**Comment by altermo** [comment]
Also (from https://github.com/neovim/neovim/issues/28084#issuecomment-2025975136):
> `ml_get` errors are internal errors that shouldn't happen, even if a plugin is misbehaving

**Comment by auralisx** [comment]
https://github.com/user-attachments/assets/4abd1e42-0878-457c-9864-7af06615fd70

I tried to implement your quick solution but it seems like it didn't fix it for me. Maybe it's because i am using Lazyvim and they have some FileType autocmd defined and loaded before my config. But what you explained did answer why my neovim is behaving like that. I still don't understand why that buffer is appearing at the top like that out of nowhere. Didn't even knew it was another buffer at first, but hope it will be fixed soon. Thanks for the help though.

**Comment by altermo** [comment]
Possible quick fix, override `vim.filetype.get_option`:
```lua
local get_option=vim.filetype.get_option
rawset(vim.filetype,'get_option',function (ft,opt)
    if ft=='norg' then return vim.api.nvim_get_option_value(opt,{}) end
    return get_option(ft,opt)
end)
```

**Comment by auralisx** [comment]
Thanks the override worked. :fire:
